### ISSUE TITLE
RSpecCommand::command runs the command again for every example

### ISSUE THREAD

**Issue by anttiviljami** [coderanger/rspec-command#1]
Consider a simple program called iterator, which each time it's called it will increment its value by 1 and output the number:

``` ruby
describe 'iterator' do
  command 'iterator' 

  its(:stdout) { is_expected.to eq '1' }
  its(:stderr) { is_expected.to eq '' }
end
```

Tests pass.

But if I reset the iterator and run the examples in a different order:

``` ruby
describe 'iterator' do
  command 'iterator' 

  its(:stderr) { is_expected.to eq '' }
  its(:stdout) { is_expected.to eq '1' }
end
```

Tests fail, because iterator has actually been called each time an example was run. subject[:stdout] is 2 by the time it gets to line

```
  its(:stdout) { is_expected.to eq '1' }
```

Instead of running the command again for every command. We should run the command once and save the output for all examples within a describe block.

**Comment by coderanger** [comment]
This is expected behavior and matches other RSpec helpers (e.g. `let`, `subject`). If you want it to run once, put both matchers in a single example:

``` ruby
it do
  expect(subject.stdout).to eq '1'
  expect(subject.stderr).to eq ''
end
```
